<?php

/*

OK        1. SE JÁ EXISTE HORÁRIO PADRÃO NA MESMA DATA, NÃO FAZER INSERT, MAS SIM UPDATE (NÃO DUPLICAR)
OK        2. AO FAZER UPDATE DO HORÁRIO PADRÃO, INSERIR NA TABELA SITUACAOPADRAO (ATUALMENTE APENAS EM SITUACAOREAL)
OK         3. SELECIONAR O PADRÃO DE MAIOR DATA, MENOR OU IGUAL A HOJE

*/



/*

HORÁRIO PADRÃO

1. DATA SELECIONADA WHERE UNIDADE + SERVIÇO
2. PEGAR TODAS AS DATAS INICIAIS MENORES QUE A DATA SELECIONADA
3. PEGAR A MAIOR DATA (MAIS ATUAL)
4. DEFINIDO HORÁRIO PADRÃO

5. DEFINIR COMO ATIVO = TRUE

01/04 - AGRONÔMICA - VACINA - 8 -12 -13 - 17 - FALSE
05/05 - AGRONÔMICA - VACINA - 7 - 0 - 0 - 17 - TRUE

CONSULTAR HORÁRIO PADRÃO - PADRÃO DESDE 05/05


HORÁRIO REAL
NO DIA ATUAL, BUSCA O PADRÃO, BD VAZIO
DIAS FUTUROS ???

PREENCHER HORÁRIO PADRÃO ATÉ...
SOBRESCREVER HORÁRIO REAL COM NOVO HORÁRIO PADRÃO



*/







