<?php

/*

ROADMAP 07/05/2021

 OK     - ACRESCENTAR O ALO SAÚDE AOS UPDATES
        - HORÁRIO DA UNIDADE RESTRINGE OS DEMAIS
        - UPDATE SEPARADO POR SERVIÇO, ALTERAR APENAS SE CLICAR OK
        - TELA PARA ALÔ SAÚDE

        - FUNÇÃO REPETIR, SELECIONAR APENAS DIAS ÚTEIS
        - ADMIN: ABRIR CALENDÁRIO
        - ADICIONAR MAIS TIPOS DE UNIDADES, ADICIONAR MAIS TIPOS DE SERVIÇOS
        - LÓGICA INTERNA DE VALORES H1/H2/H3/H4
        - LAYOUT DO HORÁRIO PADRÃO (DENTRO DO CARD)
        - SLIDER DEVE ALTERAR VALOR EM VERDE
        - CRIAR REGISTRO DE OCORRÊNCIAS: CLASSIFICAÇÃO E BOOLEAN EM SITUACAOREAL
        - LOG COM ALTERAÇÕES DO DIA
        - ACESSOS E PERMISSÕES









OK        1. SE JÁ EXISTE HORÁRIO PADRÃO NA MESMA DATA, NÃO FAZER INSERT, MAS SIM UPDATE (NÃO DUPLICAR)
OK        2. AO FAZER UPDATE DO HORÁRIO PADRÃO, INSERIR NA TABELA SITUACAOPADRAO (ATUALMENTE APENAS EM SITUACAOREAL)
OK         3. SELECIONAR O PADRÃO DE MAIOR DATA, MENOR OU IGUAL A HOJE

*/



/*

HORÁRIO PADRÃO

1. DATA SELECIONADA WHERE UNIDADE + SERVIÇO
2. PEGAR TODAS AS DATAS INICIAIS MENORES QUE A DATA SELECIONADA
3. PEGAR A MAIOR DATA (MAIS ATUAL)
4. DEFINIDO HORÁRIO PADRÃO

5. DEFINIR COMO ATIVO = TRUE

01/04 - AGRONÔMICA - VACINA - 8 -12 -13 - 17 - FALSE
05/05 - AGRONÔMICA - VACINA - 7 - 0 - 0 - 17 - TRUE

CONSULTAR HORÁRIO PADRÃO - PADRÃO DESDE 05/05


HORÁRIO REAL
NO DIA ATUAL, BUSCA O PADRÃO, BD VAZIO
DIAS FUTUROS ???

PREENCHER HORÁRIO PADRÃO ATÉ...
SOBRESCREVER HORÁRIO REAL COM NOVO HORÁRIO PADRÃO



*/

/* INSERT DE NOVO HORÁRIO PADRÃO POR SERVIÇO?
SE HORÁRIO ALTERADO, REGISTRAR NOVO HORÁRIO PADRÃO





